config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, 
  skip: [:registrations, :password], #サインアップとパスワード設定機能をスキップ
  controllers: {sessions: 'admin/sessions'}

  namespace :admin do
    get 'dashboards', to: 'dashboards#top'
    resources :users, only: [:show,:index] do
      member do
        patch 'withdraw' => 'users#withdraw'
        patch 'rejoin' => 'users#rejoin'
      end
    end 
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :destroy]
  end



  scope module: :public do
    devise_for :users, controllers: { sessions: 'public/sessions' } #Deviseのデフォルトのsessionsコントローラーをカスタムコントローラー(public/sessions)に置き換え

    root to: 'homes#top'
  
    get 'homes/about'

    #検索ボタンが押された時、Searchesコントローラーのsearch実行
    get "search" => "searches#index"

    resources :users, only: [:index,:show, :edit, :update ] do
      resource :relationships, only: [:create, :destroy] #フォロー機能
      member do
        get "followings" => "relationships#followings",as: "followings" #フォロー一覧
  	    get "followers" => "relationships#followers",as: "followers" #フォロワー一覧
        get 'deactivate' => 'users#deactivate' # ユーザー退会確認画面
        patch 'withdraw' => 'users#withdraw' # ユーザー退会　論理削除
      end
    end

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end

    resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
      resource :group_members, only: [:create, :destroy]
      resource :group_join_requests, only: [:create, :destroy]
    end
    get "groups/:id/display_join_requests" => "groups#display_join_requests", as: :display_join_requests
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  # 投稿画像
  has_one_attached :image, dependent: :purge_later

  # アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # バリデーション
  validates :title, presence: true 
  validates :body, presence: true,  length: { maximum: 6000 }
  validates :image, presence: true

  # 投稿画像用
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end

  # 投稿検索用 
  def self.search_for(query, method) #self →Post自体をさしている

    if method == 'perfect' #検索方法が'perfect'（完全一致）の場合に実行
      Post.where(title: query).order(created_at: :desc) #titleカラムがqueryと完全に一致するレコードを検索

    elsif method == 'forward' #検索方法が'forward'（前方一致）の場合に実行
      Post.where('title LIKE ?', query+'%').order(created_at: :desc) #titleカラムがqueryで始まるレコードを検索

    elsif method == 'backward' #検索方法が'backward'（後方一致）の場合に実行
      Post.where('title LIKE ?', '%'+query).order(created_at: :desc) #titleカラムがqueryで終わるレコードを検索

    else #上記以外の場合、部分一致の検索処理を実行
      Post.where('title LIKE ?', '%'+query+'%').order(created_at: :desc) #titleカラムがqueryを含むレコードを検索
    end
  end

  #いいね機能用
  def liked_by?(user)
    likes.exists?(user_id: user.id) #likesテーブル内に引数で渡されたuser.idが存在するか　（存在している：true していない：false)
  end


end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin' #/views/layouts/　にあるapplication.html.erbの代わりにadmin.html.erbを使用する
  before_action :authenticate_admin!

  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path, notice: '投稿を削除しました。'
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
  
  <h1>投稿管理</h1>
  <div class="container">    
    <% @posts.each do |post| %>
      <a href="<%= admin_post_path(post) %>" class="list-group-item list-group-item-action border border-primary">

        <div class="row align-items-center">
          <div class="col-md-4">
            <%= image_tag post.get_image(300,300) %>
          </div>

          <div class="col-md-8" style="word-break: break-all;">

            <p class ="mb-1 " style="font-size: 1.5rem; font-weight: bold;">
              <%= post.title %>
            </p>

            <p class= " mb-1 w-100 text-wrap">
              <%# 投稿の本文を短く切り取る %>
              <%= truncate(post.body, length: 100) %>
            </p>

            <p class="text-muted small">投稿者: <%= post.user.name %> | <%= post.created_at.strftime("%Y/%m/%d %H:%M") %></p>
            <p class="text-muted small">コメント数:<%= post.comments.count %></p>
          </div>
        </div>
      </a>  
    <% end %>
    <h2 class=" text-dark ">
      <%= paginate @posts, class: "pagination" %>
    </h2>
  </div>

app/views/admin/posts/show.html.erb
<div class="container">

  <%# 投稿内容表示 %>
  <div class="row bg-secondary text-white m-5">
    <div class="col-md-1 p-3">
      <%# 左側投稿者イメージ画像、投稿者表示 %>
      <%= link_to user_path(@post.user.id) do%> 
        <%= image_tag @post.user.get_profile_image(100,100) %><br>
      <% end %>
      投稿者:<br> 
      <%= @post.user.name %><br>
    </div>
    <%# 右側投稿画像、タイトル本文表示 %>
    <div class="col-md-10 offset-md-1 p-3 bg-light text-dark">
      <%= image_tag @post.get_image(600,600), class: "img-fluid" %><br>
      タイトル: <%= @post.title %><br>
      コメント数：<%= @post.comments.count %>
      本文: <%= @post.body %><br>
        <% if admin_signed_in? %>
          <td><%= link_to "削除", admin_post_path(@post), class:"btn btn-sm btn-danger", method: :delete, data: { confirm: "本当に削除しますか？" }%></td>
        <% end %>
    </div>
  </div>

  <%# コメント表示 %>
  <div class="row bg-light text-dark m-5">

    <div class="col-md-12 p-3 bg-light text-dark">
      <div>
        <% @post.comments.each do |comment| %>
        <div class="row">
          <div class="col">
            <p><%= image_tag comment.user.get_profile_image(100,100) %></p>
          </div>

          <div class="col">
            <p class="text-muted small">投稿ユーザー: <%= comment.user.name %><br>
            投稿日: <%= comment.created_at.strftime('%Y/%m/%d') %></p>
            <%= comment.content %><br>

            <% if admin_signed_in? %> 
              <div class ="row">
                <div class="col-md-10"></div>
                <div class="col-md-2 ">
                  <%= link_to "削除", admin_post_comment_path(comment.post, comment), class: "btn btn-sm btn-danger", method: :delete, data: { confirm: "本当に削除しますか？" } %>
                </div>
              </div> 
            <% end %>

          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>


</div>