config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, 
  skip: [:registrations, :password], #サインアップとパスワード設定機能をスキップ
  controllers: {sessions: 'admin/sessions'}

  namespace :admin do
    get 'dashboards', to: 'dashboards#top'
    resources :users, only: [:show,:index] do
      member do
        patch 'withdraw' => 'users#withdraw'
        patch 'rejoin' => 'users#rejoin'
      end
    end 
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :destroy]
  end



  scope module: :public do
    devise_for :users, controllers: { sessions: 'public/sessions' } #Deviseのデフォルトのsessionsコントローラーをカスタムコントローラー(public/sessions)に置き換え

    root to: 'homes#top'
  
    get 'homes/about'

    #検索ボタンが押された時、Searchesコントローラーのsearch実行
    get "search" => "searches#index"

    resources :users, only: [:index,:show, :edit, :update ] do
      resource :relationships, only: [:create, :destroy] #フォロー機能
      member do
        get "followings" => "relationships#followings",as: "followings" #フォロー一覧
  	    get "followers" => "relationships#followers",as: "followers" #フォロワー一覧
        get 'deactivate' => 'users#deactivate' # ユーザー退会確認画面
        patch 'withdraw' => 'users#withdraw' # ユーザー退会　論理削除
      end
    end

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end

    resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
      resource :group_members, only: [:create, :destroy]
      resource :group_join_requests, only: [:create, :destroy]
    end
    get "groups/:id/display_join_requests" => "groups#display_join_requests", as: :display_join_requests
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_form.html.erb
  <%# 検索用フォーム %>

  <div class="search-form">
    <% if user_signed_in? %>
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :query %>
        <%= f.select :model, options_for_select({ "User" => "user", "Post" => "post" }) %> 
        <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %> 
        <%= f.submit '検索' %>
      <% end %>
    <% end %>
  </div>

app/views/searches/index.html.erb
<%# 検索結果一覧表示 %>
<% if @model == 'user' %>
	<h2>User 検索結果 一覧 </h2>
  <p>検索文字 "<%= @query %>" </p>
  <div class="container mt-4 ">
    <h3 class="mb-5 text-center ">ユーザー一覧</h3>
    <%# ユーザー一覧呼び出し %>
    <%= render 'shared/user_list', users: @search_results %>
  </div>
<% elsif @model == 'post' %>
	<h2>Post 検索結果 一覧 </h2>
  <p>検索文字 "<%= @query %>" </p>
  <div class="container mt-4 ">
    <h3 class="mb-5 text-center ">投稿一覧</h3>
    <div class="text-end mb-5">
      <%= link_to "新規投稿", new_post_path, class: "btn btn-primary" %>
    </div>
    <%# 投稿一覧呼び出し %>
   <%= render 'shared/post_list', posts: @search_results %>
  </div>
<% end %>