config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, 
  skip: [:registrations, :password], #サインアップとパスワード設定機能をスキップ
  controllers: {sessions: 'admin/sessions'}

  namespace :admin do
    get 'dashboards', to: 'dashboards#top'
    resources :users, only: [:show,:index] do
      member do
        patch 'withdraw' => 'users#withdraw'
        patch 'rejoin' => 'users#rejoin'
      end
    end 
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :destroy]
  end



  scope module: :public do
    devise_for :users, controllers: { sessions: 'public/sessions' } #Deviseのデフォルトのsessionsコントローラーをカスタムコントローラー(public/sessions)に置き換え

    root to: 'homes#top'
  
    get 'homes/about'

    #検索ボタンが押された時、Searchesコントローラーのsearch実行
    get "search" => "searches#index"

    resources :users, only: [:index,:show, :edit, :update ] do
      resource :relationships, only: [:create, :destroy] #フォロー機能
      member do
        get "followings" => "relationships#followings",as: "followings" #フォロー一覧
  	    get "followers" => "relationships#followers",as: "followers" #フォロワー一覧
        get 'deactivate' => 'users#deactivate' # ユーザー退会確認画面
        patch 'withdraw' => 'users#withdraw' # ユーザー退会　論理削除
      end
    end

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end

    resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
      resource :group_members, only: [:create, :destroy]
      resource :group_join_requests, only: [:create, :destroy]
    end
    get "groups/:id/display_join_requests" => "groups#display_join_requests", as: :display_join_requests
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController

  layout 'admin' #/views/layouts/　にあるapplication.html.erbの代わりにadmin.html.erbを使用する

  before_action :authenticate_admin!
  def index
      @users = User.all
  end

end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<h1>管理者ダッシュボード</h1>


<div class="container"> 
  <h2>ユーザー一覧</h2>
    <% @users.each do |user| %>
      <div class="row p-2 align-items-center border border-primary">
            <div class="col-md-4">
              <%= image_tag user.get_profile_image(300,300) %>
            </div>

            <div class="col-md-7">
              <div>
                ユーザー名: <%= user.name %> <br>
                <% if user.introduction.present? %>
                  introduction: <%= user.introduction %>
                <% end %>
                退会フラグ：<%= user.is_active%>
              </div>
            </div>

            <div class="col-md-1">
              <div class="row">
                <button type="button" class="btn btn-danger btn-lg btn-block" >
                  <%= link_to withdraw_admin_user_path(user), method: :patch, data: { confirm: '退会状態にします。よろしいですか？' } do %>
                    <i>退会</i>
                  <%end%>
                </button>
                <button type="button" class="btn btn-success btn-lg btn-block" >
                  <%= link_to rejoin_admin_user_path(user), method: :patch, data: { confirm: '入会状態にします。よろしいですか？' } do %>
                    <i>入会</i>
                  <%end%>
                </button>
              </div>
            </div>

          </div>
       
      </a>
    <% end %> 
  </div>
</div>

app/views/admin/dashboards/top.html.erb
<h1>管理者用ページ</h1>