config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, 
  skip: [:registrations, :password], #サインアップとパスワード設定機能をスキップ
  controllers: {sessions: 'admin/sessions'}

  namespace :admin do
    get 'dashboards', to: 'dashboards#top'
    resources :users, only: [:show,:index] do
      member do
        patch 'withdraw' => 'users#withdraw'
        patch 'rejoin' => 'users#rejoin'
      end
    end 
    resources :posts, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
    resources :groups, only: [:index, :destroy]
  end



  scope module: :public do
    devise_for :users, controllers: { sessions: 'public/sessions' } #Deviseのデフォルトのsessionsコントローラーをカスタムコントローラー(public/sessions)に置き換え

    root to: 'homes#top'
  
    get 'homes/about'

    #検索ボタンが押された時、Searchesコントローラーのsearch実行
    get "search" => "searches#index"

    resources :users, only: [:index,:show, :edit, :update ] do
      resource :relationships, only: [:create, :destroy] #フォロー機能
      member do
        get "followings" => "relationships#followings",as: "followings" #フォロー一覧
  	    get "followers" => "relationships#followers",as: "followers" #フォロワー一覧
        get 'deactivate' => 'users#deactivate' # ユーザー退会確認画面
        patch 'withdraw' => 'users#withdraw' # ユーザー退会　論理削除
      end
    end

    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end

    resources :groups, only: [:index, :show, :new, :create, :edit, :update, :destroy] do 
      resource :group_members, only: [:create, :destroy]
      resource :group_join_requests, only: [:create, :destroy]
    end
    get "groups/:id/display_join_requests" => "groups#display_join_requests", as: :display_join_requests
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - gamer-bosyu-kaijo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%# FontAwesomeの導入 %>
  <script src="https://kit.fontawesome.com/81b2a4006b.js" crossorigin="anonymous"></script>
  
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

  <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
        <div class="container">
          <a class ="navbar-brand" href="/admin/dashboards">
           <span>"ゲーマー募集会所"admin</span>
          </a>
          <%# ドロップダウンを設定 %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          
            <ul class="navbar-nav ml-auto"> 

              <% if admin_signed_in? %> 
                <li>
                  <a class="nav-link text-light" href="<%= admin_users_path %>" >
                   <i class="fa-solid fa-house"></i>
                    ユーザー管理
                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= admin_groups_path %>" >
                    <i class="fa-solid fa-house"></i>
                    グループ管理
                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= admin_posts_path %>">
                    <i class="fa-solid fa-house"></i>
                    投稿管理
                  </a>
                </li>

                
                <li>
                 <%= link_to  destroy_admin_session_path, method: :delete, class:"nav-link text-light" do%>
                  <i class="fa-solid fa-right-from-bracket"></i>
                  ログアウト
                  <%end%>
                </li>

              <%else%>
                <li>
                  <a class="nav-link text-light" href="<%= new_admin_session_path %>" >
                    <i class="fa-solid fa-house"></i>
                   ログイン
                  </a>
                </li>
              <%end%>

            </ul>
          </div>
        </div>
        
      </nav>
    </header>
    
    <%# フラッシュメッセージ表示 %>
    <div id="flash-messages" class="min-vh-10 d-flex align-items-center justify-content-center">
      <p class="text-success font-weight-bold"><%= flash[:notice] %></p>
      <p class="text-danger font-weight-bold"><%= flash[:alert] %></p>
    </div>
    
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamerBosyuKaijo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# FontAwesomeの導入 %>
    <script src="https://kit.fontawesome.com/81b2a4006b.js" crossorigin="anonymous"></script>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
        <div class="container">
          <a class ="navbar-brand" href="/">
           <span>ゲーマー募集会所</span>
          </a>
          <%# ドロップダウンを設定 %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          
            <ul class="navbar-nav ml-auto"> 

              <% if user_signed_in? %> 
                <li>
                  <a class="nav-link text-light" href="<%= homes_about_path %>" >
                   <i class="fa-solid fa-house"> about</i>

                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= groups_path %>" >
                    <i class="fa-solid fa-user-group"> グループ一覧</i>
                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= posts_path %>">
                    <i class="fa-solid fa-star"> 投稿一覧</i>
                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= new_post_path %>">
                    <i class="fa-solid fa-paper-plane"> 新規投稿</i>
                  </a>
                </li>
                
                <% if user_signed_in? %>
                  <a class="nav-link text-light" href="<%= user_path(current_user) %>">
                    <i class="fa-solid fa-user"> マイページ</i>
                  </a>
                <% end %>

                <li>
                 <%= link_to  destroy_user_session_path, method: :delete, class:"nav-link text-light" do%>
                    <i class="fa-solid fa-right-from-bracket">  ログアウト</i>
                    <%end%>
                </li>

              <%else%>
                <li>
                  <a class="nav-link text-light" href="<%= homes_about_path %>" >
                   <i class="fa-solid fa-house"> about</i>
                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= posts_path %>">
                    <i class="fa-solid fa-star"> 投稿一覧</i>
                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= new_user_session_path %>" >
                    <i class="fa-solid fa-right-to-bracket">  ログイン</i>
                  </a>
                </li>

                <li>
                  <a class="nav-link text-light" href="<%= new_user_registration_path %>" >
                    <i class="fa-solid fa-address-card"> 新規登録</i>
                  </a>
                </li>
              <%end%>

            </ul>
          </div>
        </div>
        
      </nav>
    </header>
    
    <%# フラッシュメッセージ表示 %>
    <div id="flash-messages" class="min-vh-10 d-flex align-items-center justify-content-center">
      <p class="text-success font-weight-bold"><%= flash[:notice] %></p>
      <p class="text-danger font-weight-bold"><%= flash[:alert] %></p>
    </div>



    <%= yield %>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p></p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>